spring.application.name=patient-management-service

server.servlet.context-path=/api/v1

server.port=5201

spring.config.import=optional:file:.env[.properties]

# DATABASE CONFIGURATION
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.database=${POSTGRES_DB}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.sql.init.platform=postgres
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Always compare current entity with DB model
spring.sql.init.mode=always

# put data.sql values in DB
spring.sql.defer-datasource-initialization=true
